-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.HDPython_core.all;
use work.register_t_pack.all;
use work.v_symbol_pack.all;


package system_globals_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class system_globals -------------------------

type system_globals is record 
    reg : register_t;
    rst : std_logic;
end record;
    
    
  constant system_globals_null : system_globals:= (
    reg => register_t_ctr,
    rst => std_logic_ctr(0, 1)
  );


    type system_globals_a is array (natural range <>) of system_globals;
        



  function system_globals_ctr  return system_globals;
  procedure pull_01 (signal clk: in std_logic; self : inout system_globals; signal data_IO :  in  system_globals);
  procedure push_01 (signal clk: in std_logic; self : inout system_globals; signal data_IO :  out  system_globals);
  procedure pull_11 (signal clk: in std_logic;  signal self : inout system_globals; signal data_IO :  in  system_globals);
  procedure push_11 (signal clk: in std_logic;  signal self : inout system_globals; signal data_IO :  out  system_globals);
------- End Psuedo Class system_globals -------------------------
-------------------------------------------------------------------------


end system_globals_pack;


package body system_globals_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class system_globals -------------------------
function system_globals_ctr  return system_globals is
    variable ret : system_globals := system_globals_null; 
  begin 
     return ret;
 
end function;

procedure pull_01 (signal clk: in std_logic; self : inout system_globals; signal data_IO :  in  system_globals) is
   
  begin 
 self   :=  data_IO; 
end procedure;

procedure push_01 (signal clk: in std_logic; self : inout system_globals; signal data_IO :  out  system_globals) is
   
  begin 
 data_IO  <=  self; 
end procedure;

procedure pull_11 (signal clk: in std_logic;  signal self : inout system_globals; signal data_IO :  in  system_globals) is
   
  begin 
 self   <=  data_IO; 
end procedure;

procedure push_11 (signal clk: in std_logic;  signal self : inout system_globals; signal data_IO :  out  system_globals) is
   
  begin 
 data_IO  <=  self; 
end procedure;

------- End Psuedo Class system_globals -------------------------
  -------------------------------------------------------------------------


end system_globals_pack;

