-- XGEN: Autogenerated File

library IEEE;
library UNISIM;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use UNISIM.VComponents.all;
use ieee.std_logic_unsigned.all;
use work.HDPython_base.all;


package Var_sig_class_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class Var_sig_class -------------------------

type Var_sig_class_sig is record 
    sTest1 : std_logic_vector(31 downto 0);
    sTest2 : std_logic_vector(31 downto 0);
    sTest3 : std_logic_vector(31 downto 0);
end record;
    
    
  constant Var_sig_class_sig_null : Var_sig_class_sig:= (
    sTest1 => (others => '0'),
    sTest2 => (others => '0'),
    sTest3 => (others => '0')
  );


    type Var_sig_class_sig_a is array (natural range <>) of Var_sig_class_sig;
        


type Var_sig_class is record 
    vTest1 : std_logic_vector(31 downto 0);
    vTest2 : std_logic_vector(31 downto 0);
    vTest3 : std_logic_vector(31 downto 0);
end record;
    
    
  constant Var_sig_class_null : Var_sig_class:= (
    vTest1 => (others => '0'),
    vTest2 => (others => '0'),
    vTest3 => (others => '0')
  );


    type Var_sig_class_a is array (natural range <>) of Var_sig_class;
        

-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
  procedure f2_01 (Signal self_sig :  in  Var_sig_class_sig; signal self_sig_sTest2 :  out  std_logic_vector(31 downto 0); self :  inout  Var_sig_class; signal x :  in  std_logic_vector(31 downto 0));
  procedure f1_0 (Signal self_sig :  in  Var_sig_class_sig; signal self_sig_sTest1 :  out  std_logic_vector(31 downto 0); self :  inout  Var_sig_class);
------- End Psuedo Class Var_sig_class -------------------------
-------------------------------------------------------------------------


end Var_sig_class_pack;


package body Var_sig_class_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class Var_sig_class -------------------------
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
-- empty procedure removed. name: 'pull'
-- empty procedure removed. name: 'push'
procedure f1_0 (Signal self_sig :  in  Var_sig_class_sig; signal self_sig_sTest1 :  out  std_logic_vector(31 downto 0); self :  inout  Var_sig_class) is
   
  begin 
 self.vTest1  :=  std_logic_vector(to_unsigned(5, self.vTest1'length));
  self_sig_sTest1  <=  std_logic_vector(to_unsigned(4, self_sig_sTest1'length));
   
end procedure;

procedure f2_01 (Signal self_sig :  in  Var_sig_class_sig; signal self_sig_sTest2 :  out  std_logic_vector(31 downto 0); self :  inout  Var_sig_class; signal x :  in  std_logic_vector(31 downto 0)) is
   
  begin 
 self.vTest2 := x;
  self_sig_sTest2 <= x;
   
end procedure;

------- End Psuedo Class Var_sig_class -------------------------
  -------------------------------------------------------------------------


end Var_sig_class_pack;

