-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.HDPython_core.all;
use work.v_symbol_pack.all;


entity var_sig_tb is 
end entity;



architecture rtl of var_sig_tb is

--------------------------var_sig_tb-----------------
--------------------------clkgen-----------------
  signal clkgen_clk : std_logic := std_logic_ctr(0, 1); 
-------------------------- end clkgen-----------------
--------------------------vs_impl-----------------
  signal vs_impl_clk : std_logic := std_logic_ctr(0, 1); 
-------------------------- end vs_impl-----------------
-------------------------- end var_sig_tb-----------------

begin
  -- begin architecture
  -- end architecture

  clkgen : entity work.clk_generator port map (
    clk => clkgen_clk
  );
  
  vs_impl : entity work.var_sig_impl port map (
    clk => vs_impl_clk
  );
  vs_impl_clk <= clkgen_clk;
  
end architecture;