-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.HDPython_core.all;
use work.v_symbol_pack.all;


entity clk_generator is 
  port(
    clk :  out  std_logic := std_logic_ctr(0, 1)
  );
end entity;



architecture rtl of clk_generator is

--------------------------clk_generator-----------------
-------------------------- end clk_generator-----------------

begin
  -- begin architecture
  
-----------------------------------
proc : process
  begin
    clk <= '1';
    wait for  10 ns;
    clk <= '0';
    wait for  10 ns;
    
  end process;
  -- end architecture

end architecture;