-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.HDPython_core.all;
use work.v_symbol_pack.all;


package addr_data_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class addr_data -------------------------

type addr_data is record 
    address : slv32;
    data : slv32;
end record;
    
    
  constant addr_data_null : addr_data:= (
    address => std_logic_vector_ctr(0, 32),
    data => std_logic_vector_ctr(0, 32)
  );


    type addr_data_a is array (natural range <>) of addr_data;
        

  function addr_data_ctr  return addr_data;
  procedure pull_01 (self : inout addr_data; signal data_IO :  in  addr_data);
  procedure push_01 (self : inout addr_data; signal data_IO :  out  addr_data);
  procedure pull_11 (signal self : inout addr_data; signal data_IO :  in  addr_data);
  procedure push_11 (signal self : inout addr_data; signal data_IO :  out  addr_data);
------- End Psuedo Class addr_data -------------------------
-------------------------------------------------------------------------


end addr_data_pack;


package body addr_data_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class addr_data -------------------------
function addr_data_ctr  return addr_data is
    variable ret : addr_data := addr_data_null; 
  begin 
     return ret;
 
end function;

procedure pull_01 (self : inout addr_data; signal data_IO :  in  addr_data) is
   
  begin 
 self   :=  data_IO; 
end procedure;

procedure push_01 (self : inout addr_data; signal data_IO :  out  addr_data) is
   
  begin 
 data_IO  <=  self; 
end procedure;

procedure pull_11 (signal self : inout addr_data; signal data_IO :  in  addr_data) is
   
  begin 
 self   <=  data_IO; 
end procedure;

procedure push_11 (signal self : inout addr_data; signal data_IO :  out  addr_data) is
   
  begin 
 data_IO  <=  self; 
end procedure;

------- End Psuedo Class addr_data -------------------------
  -------------------------------------------------------------------------


end addr_data_pack;

