-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.HDPython_core.all;
use work.registerT_pack.all;
use work.v_symbol_pack.all;


package globals_t_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class globals_t -------------------------

type globals_t is record 
    clk : std_logic;
    reg : registerT;
    rst : std_logic;
end record;
    
    
  constant globals_t_null : globals_t:= (
    clk => std_logic_ctr(0, 1),
    reg => registerT_ctr,
    rst => std_logic_ctr(0, 1)
  );


    type globals_t_a is array (natural range <>) of globals_t;
        

  function globals_t_ctr  return globals_t;
  procedure pull_01 (self : inout globals_t; signal data_IO :  in  globals_t);
  procedure push_01 (self : inout globals_t; signal data_IO :  out  globals_t);
  procedure pull_11 (signal self : inout globals_t; signal data_IO :  in  globals_t);
  procedure push_11 (signal self : inout globals_t; signal data_IO :  out  globals_t);
------- End Psuedo Class globals_t -------------------------
-------------------------------------------------------------------------


end globals_t_pack;


package body globals_t_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class globals_t -------------------------
function globals_t_ctr  return globals_t is
    variable ret : globals_t := globals_t_null; 
  begin 
     return ret;
 
end function;

procedure pull_01 (self : inout globals_t; signal data_IO :  in  globals_t) is
   
  begin 
 self   :=  data_IO; 
end procedure;

procedure push_01 (self : inout globals_t; signal data_IO :  out  globals_t) is
   
  begin 
 data_IO  <=  self; 
end procedure;

procedure pull_11 (signal self : inout globals_t; signal data_IO :  in  globals_t) is
   
  begin 
 self   <=  data_IO; 
end procedure;

procedure push_11 (signal self : inout globals_t; signal data_IO :  out  globals_t) is
   
  begin 
 data_IO  <=  self; 
end procedure;

------- End Psuedo Class globals_t -------------------------
  -------------------------------------------------------------------------


end globals_t_pack;

