-- XGEN: Autogenerated File

library IEEE;
library work;
use IEEE.numeric_std.all;
use IEEE.std_logic_1164.all;
use ieee.std_logic_unsigned.all;
use work.HDPython_core.all;
use work.v_symbol_pack.all;


package register_t_pack is 

-------------------------------------------------------------------------
------- Start Psuedo Class register_t -------------------------

type register_t is record 
    address : slv16;
    value : slv16;
end record;
    
    
  constant register_t_null : register_t:= (
    address => std_logic_vector_ctr(0, 16),
    value => std_logic_vector_ctr(0, 16)
  );


    type register_t_a is array (natural range <>) of register_t;
        

  function register_t_ctr  return register_t;
  procedure pull_01 (self : inout register_t; signal data_IO :  in  register_t);
  procedure push_01 (self : inout register_t; signal data_IO :  out  register_t);
  procedure pull_11 (signal self : inout register_t; signal data_IO :  in  register_t);
  procedure push_11 (signal self : inout register_t; signal data_IO :  out  register_t);
------- End Psuedo Class register_t -------------------------
-------------------------------------------------------------------------


end register_t_pack;


package body register_t_pack is

-------------------------------------------------------------------------
------- Start Psuedo Class register_t -------------------------
function register_t_ctr  return register_t is
    variable ret : register_t := register_t_null; 
  begin 
     return ret;
 
end function;

procedure pull_01 (self : inout register_t; signal data_IO :  in  register_t) is
   
  begin 
 self   :=  data_IO; 
end procedure;

procedure push_01 (self : inout register_t; signal data_IO :  out  register_t) is
   
  begin 
 data_IO  <=  self; 
end procedure;

procedure pull_11 (signal self : inout register_t; signal data_IO :  in  register_t) is
   
  begin 
 self   <=  data_IO; 
end procedure;

procedure push_11 (signal self : inout register_t; signal data_IO :  out  register_t) is
   
  begin 
 data_IO  <=  self; 
end procedure;

------- End Psuedo Class register_t -------------------------
  -------------------------------------------------------------------------


end register_t_pack;

